### ISSUE TITLE
feat: add more relevant repos

### ISSUE THREAD

**Issue by SgtPooki** [ipfs-shipyard/helia-contributors#2]
- [ ] config.js should have all relevant Helia repos

**Comment by SgtPooki** [comment]
@achingbrain which other repos should we add here?

**Comment by achingbrain** [comment]
The old ipfs contributors module has a good list, plus the protocol/.github list of repos managed by Unified CI?

**Comment by SgtPooki** [comment]
I think the main ones I was missing was helia/unixfs and other helia add-on libs.. the old ipfs-contributors module is HUGE and i'm not sure which ones are still relevant..

ipfs-bitswap & ipns are two i can think of cause i've had to look at them recently

**Comment by SgtPooki** [comment]
this should be resolved thanks to https://github.com/ipfs-shipyard/helia-contributors/commit/594a919b7af78d1c3917d181126e7ecd69bc4feb
